name: "ci build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  application-tests:
    environment: production
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/renatocosta/php8-turnoverbnb:latest
        credentials:
          username: renatocosta
          password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      working-directory: ./Common/Framework
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./Common/Framework
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    #- name: Generate key
      #working-directory: ./Common/Framework    
      #run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./Common/Framework    
      run: chmod -R 777 storage
    - name: Create Database
      working-directory: ./Common/Framework
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ./Common/Framework
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --coverage-clover clover.xml  
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: 70cfecfe76fa40e5a9f350087d82b96d
        coverage-reports: clover.xml
    - uses: actions/checkout@v2
      run: | 
          pwd
