name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
        image: ghcr.io/renatocosta/php8-turnoverbnb:latest
        credentials:
          username: renatocosta
          password: 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
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      working-directory: ./Common/Framework
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./Common/Framework
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    #- name: Generate key
      #working-directory: ./Common/Framework    
      #run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./Common/Framework    
      run: chmod -R 777 storage
    - name: Create Database
      working-directory: ./Common/Framework
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ./Common/Framework
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
